[package]
name = "plat-ibkr"
version = "0.1.0"
edition = "2021"

[dependencies]
ibapi = { version = "2", features = ["sync"] }
env_logger = "0.11"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
csv = "1"
